### ISSUE TITLE
希望改进一下，能支持多行，只有3行不够用，谢谢了

### ISSUE THREAD

**Issue by uulaile** [benjypng/logseq-tablerender-plugin#1]

**Comment by benjypng** [comment]
可以给个例子吗？

**Comment by uulaile** [comment]
![Snipaste_2022-01-04_00-05-09](https://user-images.githubusercontent.com/96331996/147953246-631b38e5-f36c-4c90-a9eb-d0fad827e3c1.jpg)

**Comment by benjypng** [comment]
谢谢你！让我去调查。

**Comment by benjypng** [comment]
查到了。v1.1 没有这个问题。可以试试看。

**Comment by uulaile** [comment]
好了,谢谢,只不过Median能不能去掉，没用哦，再次谢谢了

**Comment by uulaile** [comment]
![Snipaste_2022-01-06_13-42-38](https://user-images.githubusercontent.com/96331996/148334579-20012b9b-3653-4ac7-a845-e51e616d66d3.jpg)

**Comment by benjypng** [comment]
谢了。会修改。
这是因为数字上舍入。

**Comment by benjypng** [comment]
这已在最新版本中修复! 请检查.
