### ISSUE TITLE
Seems rows mode can not output summary table

### ISSUE THREAD

**Issue by vipzhicheng** [benjypng/logseq-tablerender-plugin#10]
<img width="373" alt="image" src="https://user-images.githubusercontent.com/1209538/177262999-dffa75c9-7f2a-4918-946b-f95d576d3dcd.png">

**Comment by benjypng** [comment]
Yes, that is correct. The rows mode was introduced by a Logseq user via a PR and I think he did not program the summary in as he does not use it.

Feel free to put up a PR!
