### ISSUE TITLE
Rows mode is a bit strange

### ISSUE THREAD

**Issue by lee-b** [benjypng/logseq-tablerender-plugin#11]
Rows mode lets you enter hierarchical data, but only one complete row at a time.  So to make two rows with the same first and second column values, you need to duplicate the first and second columns.  For example:

- rows nosum
    - Category
        - Item Type
            - Supplier
                - Unit Price
     - Fresh Produce
         - Fruit and Vegetables
             - Apple
                 - Sweet Orchards Inc.
                     - 10
     - Fresh Produce
         - Fruit and Vegetables
             - Apple
                 - Not So Sweet Orchards Inc.
                     - 8

This makes very little sense.  The only real reason I would conceivably want this format is to write the data like an outline, categorizing under the same headings to organize and save typing, like so:

- rows nosum
    - Category
        - Item Type
            - Supplier
                - Unit Price
     - Fresh Produce
         - Fruit and Vegetables
             - Apple
                 - Sweet Orchards Inc.
                     - 10
                 - Not So Sweet Orchards Inc.
                     - 8

I'd suggest that this could be added as an enhancement, without breaking the current way that it works.

**Comment by benjypng** [comment]
Apologies, I don't get your example as well. The blocks on their own doesn't seem intuitive.
