### ISSUE TITLE
nosum function: is able to add more levels of heading

### ISSUE THREAD

**Issue by myjeshurun** [benjypng/logseq-tablerender-plugin#13]
as title. thanks

**Comment by benjypng** [comment]
Sorry I am not sure what you mean by more levels of heading?
________________________________
From: myjeshurun ***@***.***>
Sent: Tuesday, April 4, 2023 2:57 PM
To: hkgnp/logseq-tablerender-plugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hkgnp/logseq-tablerender-plugin] nosum function: is able to add more levels of heading (Issue #13)


as title. thanks

**Comment by myjeshurun** [comment]
I mean, while on the mode of nosum, I can only have two columns to show .
Could it be three or more columns?


Blessings in Christ,

*Jeshurun*
*我的仆人雅各，我所拣选的耶书崙哪，不要害怕！*
*Don’t be afraid, Jacob my servant; and you, Jeshurun, whom I have chosen.*

**Comment by benjypng** [comment]
Oh sure. Just nest them. Do you have a rough sample that I can draft out for you?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
