### ISSUE TITLE
A few questions more than issues; block collapse and text size

### ISSUE THREAD

**Issue by mbakstars** [benjypng/logseq-tablerender-plugin#14]
More of a couple of questions; Many thanks for this plugin! =)

is there a way to allow the block to still collapse. I have a 30+ row table 

related to above, is the font dependant on other fonts, or is there a way to decrease it. I am very new to this, but one row has parameters that I'd like to keep a certain way

**Comment by benjypng** [comment]
1) You can collapse the block that the table is on. This will collapse all the data under the table.

2) Fonts use your default Logseq settings. You can usen`custom.css` to change it.
