### ISSUE TITLE
Render Markdown in Table

### ISSUE THREAD

**Issue by pat-githubber** [benjypng/logseq-tablerender-plugin#17]
Hey, hkgnp - I love your plug-in 💚 

Just a little thing. It would be great if the table could render markdown, e.g. bold, italics, links. Here an example:
<img width="728" alt="image" src="https://github.com/hkgnp/logseq-tablerender-plugin/assets/87087327/7fc5e990-609b-4a75-8256-fc1d00736ebf">

Thank you for your work!

**Comment by benjypng** [comment]
Available in latest version.

**Comment by ghost** [comment]
@benjypng The rendering works in the content, but not in the title. Could this be added as well?

![image](https://github.com/user-attachments/assets/439fdb98-1972-4947-9b9b-2c976fa052fe)
