### ISSUE TITLE
Table not rendering when using 'data' flag

### ISSUE THREAD

**Issue by ktgibson** [benjypng/logseq-tablerender-plugin#19]
Hi!

This is an awesome plugin, thanks for your work on this! I've been running into this issue where I'm not able to render a table using the 'data' flag. I've disabled all other plugins and theme to be sure there weren't any conflicts and the issue persists.

![image](https://github.com/hkgnp/logseq-tablerender-plugin/assets/18040383/79aaaa54-61c6-438b-9b80-905262597dbd)

**Comment by benjypng** [comment]
Fixed in latest version.
