### ISSUE TITLE
Markdown links `[text](url)` doesn't render properly in cells

### ISSUE THREAD

**Issue by brake** [benjypng/logseq-tablerender-plugin#21]
I think screenshot is self explanatory:

<img width="701" alt="image" src="https://github.com/user-attachments/assets/4bbdd758-4315-4dd9-8a05-e0963e6cae25">

Also it's true for preformatted text:
<img width="185" alt="image" src="https://github.com/user-attachments/assets/93ab8f12-6480-48f7-9ae5-9ed1660825fc">

BTW, thanks for this useful plugin!

**Comment by benjypng** [comment]
Should be fixed in latest version.

**Comment by brake** [comment]
Thanks a lot! Now it works as expected!
