### ISSUE TITLE
求助, 为什么表格不出来

### ISSUE THREAD

**Issue by lishlj** [benjypng/logseq-tablerender-plugin#3]
为什么我输入了, 表格没有自动出来.  是哪里设置的问题
这是输入
![image](https://user-images.githubusercontent.com/100836036/156533540-efc25024-4485-41fc-bd5d-538dc4f558b1.png)

显示是这样的, 
![image](https://user-images.githubusercontent.com/100836036/156533888-9060d369-b48f-4bc1-a713-5ee94da4a64e.png)

Logseq版本是 , 0.5.9 + nightly 20220129

**Comment by benjypng** [comment]
Hi,
Try 'data nosum nostyle' instead of just 'data'.

**Comment by lishlj** [comment]
It works. Thanks.
