### ISSUE TITLE
Great plugin, tiny issues

### ISSUE THREAD

**Issue by johnnli** [benjypng/logseq-tablerender-plugin#4]
Hi, thanks for the plugin, quite useful!
Seems the v1.8 cannot work, reporting something like "DataBlock" error...the V1.7 works good. could you fix that?
Besides, would you please add a tiny feature to support select( and copy) the text from the table content?
Appreciate for that. :-)

**Comment by benjypng** [comment]
Please ensure your child blocks look like the below:
<img width="259" alt="Screenshot 2022-03-11 at 6 33 12 PM" src="https://user-images.githubusercontent.com/47936793/157850802-3794dec8-b07b-4aba-acd5-7510c63180ec.png">


As for select and copy the text from table, will look into it!

**Comment by benjypng** [comment]
Hi, should be fixed in v1.8.1. I presume you are referring to the calculations.
