### ISSUE TITLE
Feature request: option to make the text in each cell a link

### ISSUE THREAD

**Issue by VictorVow** [benjypng/logseq-tablerender-plugin#9]
It would be very handy if I by clicking on the text in a cell, it would zoom me into that particular block. This would enable writing additional info about the cell data without having to put it all into the cell itself.

**Comment by benjypng** [comment]
Hi, thanks for the FR. Interesting, give me some time to look into it.

**Comment by benjypng** [comment]
Apologies, would prefer the current way of being able to highlight text in a cell.
